# Generated by Django 5.1.6 on 2025-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subphase',
            name='dependencies',
            field=models.ManyToManyField(blank=True, null=True, to='api.subphase'),
        ),
    ]
