# Generated by Django 5.1.6 on 2025-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subphase_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subphase',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='api.subphase'),
        ),
    ]
