# Generated by Django 5.1.6 on 2025-02-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subphase_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
