# Generated by Django 5.1.6 on 2025-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_phase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subphase',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='subphase',
            name='takesSummaries',
            field=models.BooleanField(default=False),
        ),
    ]
