# Generated by Django 5.1.6 on 2025-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_subphase_dependencies_subphase_takessummaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subphase',
            name='takesSummaries',
            field=models.BooleanField(default=True),
        ),
    ]
