# Generated by Django 5.1.6 on 2025-02-22 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_companyprofile_companydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subphase',
            name='parent_phase_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.phase'),
        ),
    ]
