# Generated by Django 5.1.6 on 2025-02-22 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_subphase_parent_phase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='company_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.companyprofile'),
        ),
    ]
